# (min)R,G,B,(max)R,G,B,(minDelta)R,G,B,(maxDelta)R,G,B,(min)H,S,L,(max)H,S,L,(minDelta)H,S,L,(maxDelta)H,S,L
#    return f"0,0,0,255,255,255,0,0,0,30,30,30,0,0,0,255,255,255,0,0,0,30,30,30"
RGB:
    MIN:
        MIN_R=0
        MIN_G=0
        MIN_B=0
    MAX:
        MAX_R=255
        MAX_G=255
        MAX_B=255
    MIN_DELTA_RGB:
        MIN_DELTA_R=1
        MIN_DELTA_G=1
        MIN_DELTA_B=1
    MAX_DELTA_RGB:
        MAX_DELTA_R=30
        MAX_DELTA_G=30
        MAX_DELTA_B=30
HSL:
    MIN:
        MIN_H=0
        MIN_S=0
        MIN_L=0
    MAX:
        MAX_H=255
        MAX_S=255
        MAX_L=255
    MIN_DELTA_HSL:
        MIN_DELTA_H=1
        MIN_DELTA_S=1
        MIN_DELTA_L=1
    MAX_DELTA_HSL:
        MAX_DELTA_H=30
        MAX_DELTA_S=30
        MAX_DELTA_L=30
