#    (min)R,G,B,(max)R,G,B,(minDelta)R,G,B,(maxDelta)R,G,B,(min)H,S,L,(max)H,S,L,(minDelta)H,S,L,(maxDelta)H,S,L
#    return f"0,0,0,255,255,255,0,0,0,30,30,30,0,0,0,255,255,255,0,0,0,30,30,30"

config = {"configs": {
            "default_config": 
                {"name" : "default_config",
                "version" : "1.0.0",
                "username" : "cocolacre",
                "mode" : "rgb", #"hsl", "rgb_hsl" (consider BOTH color spaces' configs.)
                "min_red" : "0",
                "min_green" : "0",
                "min_blue" : "0",
                "max_red" : "255",
                "max_green" : "255",
                "max_blue" : "255",
                "min_delta_R" : "0",
                "min_delta_G" : "0",
                "min_delta_B" : "0",
                "max_delta_R" : "30",
                "max_delta_G" : "30",
                "max_delta_B" : "30",
                "min_h" : "0",
                "min_s" : "0",
                "min_l" : "0",
                "max_h" : "255",
                "max_s" : "255",
                "max_l" : "255",
                "min_delta_h" : "0",
                "min_delta_s" : "0",
                "min_delta_l" : "0",
                "max_delta_h" : "30",
                "max_delta_s" : "30",
                "max_delta_l" : "30",
                },
            "config_1":
                {"name" : "config_1",
                "version" : "1.0.0",
                "username" : "cocolacre",
                "mode" : "rgb", #"hsl", "rgb_hsl" (consider BOTH color spaces' configs.)
                "min_red" : "0",
                "min_green" : "0",
                "min_blue" : "0",
                "max_red" : "255",
                "max_green" : "255",
                "max_blue" : "255",
                "min_delta_R" : "0",
                "min_delta_G" : "0",
                "min_delta_B" : "0",
                "max_delta_R" : "30",
                "max_delta_G" : "30",
                "max_delta_B" : "30",
                "min_h" : "0",
                "min_s" : "0",
                "min_l" : "0",
                "max_h" : "255",
                "max_s" : "255",
                "max_l" : "255",
                "min_delta_h" : "0",
                "min_delta_s" : "0",
                "min_delta_l" : "0",
                "max_delta_h" : "30",
                "max_delta_s" : "30",
                "max_delta_l" : "30",
                },
            },
    "last_config_name" : "config_1"
    }
